//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_management.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class user
    {
        public int regId { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
        public string password_ { get; set; }
        public Nullable<int> age { get; set; }
        public string ocp { get; set; }
        public Nullable<int> weight_ { get; set; }
        public Nullable<double> height { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string shedule { get; set; }
        public string d_plan { get; set; }
        public string pay_type { get; set; }
        public string gender { get; set; }
        public string img_path { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }


    }
}
